openapi: 3.0.1
info:
  title: Any API
  description: ''
  version: '1.0'
servers:
  - url: https://hollard-apim-poc-3792712.azure-api.net
paths:
  /operation1:
    get:
      summary: operation1
      operationId: operation1
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]